### PR TITLE
Bump versions for two of our dependencies

### PR DESCRIPTION
**Pull request by skrobul**
this is a copy of https://github.com/skrobul/zenoss_client/pull/2 which was opened against wrong fork

via @stevekeay
> This is just so that zenoss_client will allow us to use the newer gems without conflict.

> The test suite passes all tests with the new versions.

> I don't know if this implies a different minimum ruby version than 1.8.7

### CODE REVIEW

**Comment by skrobul** [comment]
@stevekeay: this indeed breaks compatibility with ruby 1.8.7 as well as 1.9x:
https://travis-ci.org/github/RubyOpenSource/zenoss_client/jobs/683308717

Can you see if there is a way to update code to work with newer `json` ?

The 2.8.0 does not work too, but it's not caused by this PR. [The master branch build](https://travis-ci.org/github/RubyOpenSource/zenoss_client/jobs/683313026) fails on this Ruby as well.

**Comment by stevekeay** [comment]
It seems like the JSON gem only works on a limited range of ruby versions.

- Older JSON version works on old ruby but not new ruby
- Newer JSON version works on new ruby but not old ruby

The only possibilities I can see are:
- switch to a different JSON library
- don't support newer ruby
- drop support for older ruby

I vote for the last one

**Comment by skrobul** [comment]
Old ruby has been dropped in the meantime - see Taylor's commit at - https://github.com/RubyOpenSource/zenoss_client/pull/33/commits/4ac3137cd219472635046252c085c23b9d81be95

**Comment by stevekeay** [comment]
Awesome thanks @tetheredge

**Pull request merged**
