### PR TITLE
vcr: ignore hostname while replaying recordings

### PR DESCRIPTION
**Pull request by skrobul**
The `MiniTest::Runnable#name` is not available on rubies <2.0 causing [tests to fail](https://travis-ci.org/skrobul/zenoss_client/jobs/63626019), so we have to
fall back to `__name__ ` or `__NAME__` method. 

While this solve the problem with naming of the cassette, it [still fails miserably in Travis](https://travis-ci.org/skrobul/zenoss_client/jobs/63632832) but works very well [on my computer](https://gist.github.com/skrobul/c1bb54d0475ccf8ebdc1) with exactly the same settings.
It also works well on all non-19x rubies on Travis... any ideas?

### CODE REVIEW

**Comment by bjmllr** [comment]
I think we just needed `bundle exec`. https://github.com/RubyOpenSource/zenoss_client/pull/19

**Comment by skrobul** [comment]
lol, I completely forgot about it, thanks !!!

**Comment by zenchild** [comment]
You guys are really rocking on this gem! Thanks so much for taking it on.

**Comment by bjmllr** [comment]
I think we can release 0.6.0, do you both agree?

**Comment by zenchild** [comment]
Go for it.

**Comment by skrobul** [comment]
@zenchild thanks for good words and writing this gem in the first place :) btw, could you please add us to the rubygems.org so that we can push new version?

```
$ gem owner --add bjmllr@gmail.com
$ gem owner --add skrobul@skrobul.com
```

@bjmllr Absolutely! Do you think it's worth merging this PR before the actual release? While issue with ruby 1.9.x is gone, I think it's better to make VCR ignore hostname while matching the requests instead of modifying actual recordings. Alternatively, we can try to automate record modifications in all places (not just the request URI). I have attemted this in 4c3e9a23852651f39f20794740ad9094c48b5557 but it wasn't working (even after fixing [mistake](https://github.com/skrobul/zenoss_client/commit/4c3e9a23852651f39f20794740ad9094c48b5557#diff-f14ca9959ff06f3ca2ee6b9564866954R34) in line 34.

**Comment by bjmllr** [comment]
Ignoring the hostname sounds good. Can you squash this branch and make that the only change?

**Comment by skrobul** [comment]
done.

**Comment by zenchild** [comment]
@bjmllr and @skrobul You guys should be all set on rubygems.com.

**Comment by bjmllr** [comment]
Thanks @zenchild! I've published 0.6.0.

**Pull request merged**
